### PR TITLE
Update the build process

### PR DESCRIPTION
**Pull request by rpsene**
Fix the build issues and upgrade the build process

### CODE REVIEW

**Comment by WiseCrohn** [comment]
Previously the output PDF was available directly in the "build artifacts" area, whereas now you click on "build artifacts" and it gets silently downloaded, which is not as good.  Is this easily resolvable?

**Comment by WiseCrohn** [comment]
I would have thought the idea of using docker is to control and specify the build environment.  But if you just specify "latest" then it doesn't do this - things will change under our feet and potentially break at an inconvenient moment.  Is there a reason not to use a specified version of everything?

**Comment by rpsene** [comment]
@WiseCrohn 

In the build process we are using 2 images; the first one is [a base image that RVI maintains](https://github.com/riscv/riscv-docs-base-container-image) with all required dependencies and correct versions for the existing asciidoc support. 

The other one is [built on the fly](https://github.com/riscv-non-isa/riscv-rvm-csi/pull/4/files#diff-76ed074a9305c04054cdebb9e9aad2d818052b07091de1f20cad0bbac34ffb52R56) via:
docker build -t spec-schema:latest -f ./spec-schema/Dockerfile ./spec-schema

Here is where you see we calling spec-schema:latest /bin/sh like [this](https://github.com/riscv-non-isa/riscv-rvm-csi/pull/4/files#diff-76ed074a9305c04054cdebb9e9aad2d818052b07091de1f20cad0bbac34ffb52R57) . [In the Dockerfile](https://github.com/riscv-non-isa/riscv-rvm-csi/pull/4/files#diff-a704dd6380fcab3d95ff39d3e62942c309d549fbf29ffb4616414b9ff5dc571bR2), we are using Python 3.9, not latest.

**Comment by rpsene** [comment]
> 

Yes, we can improve this one.

**Review by WiseCrohn — APPROVED** [review]
LGTM

**Pull request merged**
