### PR TITLE
Interrupt support v2

### PR DESCRIPTION
**Pull request by WiseCrohn**
This mainly introduces a high-level interrupt and timer API.  There will probably be other interrupt-related functionality introduced later in low-level and driver-level APIs.

These changes go along with multiple upgrades to the YAML and its parser, to better support what we need going forward.  Each module now has its own YAML file, which makes things easier to manage rather than having a single huge YAML for the whole specification.

Key aims in the design of this high-level interrupt API:
- Support systems that are M-mode only, and those which use M/U privilege modes
- Leave all hardware-specific implementation to the BSP, so the API fully supports portable code (so details of routing interrupts, configuring parameters like edge / level triggered etc form part of the BSP implementation and are not on the API)
- Functions should be reentrant / thread-safe: so one instance per hart, and separate context structures (memory spaces) for each instance, passed in at initialization time.
- Also support the latest version of the RISC-V privileged spec (1.12 currently in review) where hardware support for handling traps in U-mode is removed. Traps must be handled in M-mode and passed to U-mode using MRET where applicable. This approach is backwards-compatible with older versions of the spec.

Wider assumptions about the "embedded" systems we support:
- No virtualisation
- No virtual memory / address translation / MMU
- S/VS/HS privilege modes not applicable

To see the output specification in PDF form, get the latest from github actions here: https://github.com/riscv-non-isa/riscv-rvm-csi/actions/workflows/build-pdf.yml

### CODE REVIEW

**Comment by ghost** [comment]
Functions should be reentrant / thread-safe: so one instance per hart, and separate context structures (memory spaces) for each instance, passed in at initialization time.
- For addressing interrupt reentrant case,  there must be specified stack size for interrupt routine use..  Could we need to specify this ?
- For the interrupt entry mode , shall we need to support both single entry and vector entry  ?

**Comment by ghost** [comment]
Support systems that are M-mode only, and those which use M/U privilege modes
Also support the latest version of the RISC-V privileged spec (1.12 currently in review) where hardware support for handling traps in U-mode is removed. Traps must be handled in M-mode and passed to U-mode using MRET where applicable. This approach is backwards-compatible with older versions of the spec.
- For MCU only with M mode ,  it is no problem since all firmware runing in M mode.
- For MCU using M mode and U mode,  it requires a firmware runing in M mode to deal all interrupt from U mode and M mode. it plays role as OpenSBI similarly.  So, the firmware should provide a interrupt register APIs to allow user programme to register interrupt that will be recorded in M mode... For my view, it is out of our scope in RVM_CSI specification V1.
-

**Comment by WiseCrohn** [comment]
> * For addressing interrupt reentrant case,  there must be specified stack size for interrupt routine use..  Could we need to specify this ?

There are specified stacks for interrupt routine use, and the user determines their size (see parameters mstack, mstack_size, ustack and ustack_size passed into csi_interrupts_init).  Does this address your question?

> * For the interrupt entry mode , shall we need to support both single entry and vector entry  ?

Yes, I think both are supported.  We state that there is a preference for vectored.

**Comment by WiseCrohn** [comment]
> * For MCU using M mode and U mode,  it requires a firmware runing in M mode to deal all interrupt from U mode and M mode. it plays role as OpenSBI similarly.  So, the firmware should provide a interrupt register APIs to allow user programme to register interrupt that will be recorded in M mode... For my view, it is out of our scope in RVM_CSI specification V1.

Managing privilege modes may require firmware, which is out of scope for RVM-CSI.  The interrupt handling code which I am proposing here is self-contained and does not depend on such firmware; while supporting the possibility of handling interrupts at 2 different privilege levels (which is simply supporting the features that have been specified in the standard RISC-V hardware).  I feel this may be useful, and it is too restricting to say all microcontrollers are M-mode only.  It is not possible to create a secure system without the use of privilege modes, and security is important for microcontrollers.

**Comment by ghost** [comment]
- For addressing interrupt reentrant case, there must be specified stack size for interrupt routine use.. Could we need to specify this ?
There are specified stacks for interrupt routine use, and the user determines their size (see parameters mstack, mstack_size, ustack and ustack_size passed into csi_interrupts_init). Does this address your question?

- For the interrupt entry mode , shall we need to support both single entry and vector entry ?
Yes, I think both are supported. We state that there is a preference for vectored.

- I have no opinion on telling interrupt stack size by calling csi_interrupt_init functions.. I am just only  curious  to how many user know the value 's definion if they have no knowledge in low level..

**Comment by ghost** [comment]
For MCU using M mode and U mode, it requires a firmware runing in M mode to deal all interrupt from U mode and M mode. it plays role as OpenSBI similarly. So, the firmware should provide a interrupt register APIs to allow user programme to register interrupt that will be recorded in M mode... For my view, it is out of our scope in RVM_CSI specification V1.
Managing privilege modes may require firmware, which is out of scope for RVM-CSI. The interrupt handling code which I am proposing here is self-contained and does not depend on such firmware; while supporting the possibility of handling interrupts at 2 different privilege levels (which is simply supporting the features that have been specified in the standard RISC-V hardware). I feel this may be useful, and it is too restricting to say all microcontrollers are M-mode only. It is not possible to create a secure system without the use of privilege modes, and security is important for microcontrollers.

- what would we take into account is how to help user develop secure application on MCU with two privilge (M & U) . it is better to do that at next stage.

**Comment by WiseCrohn** [comment]
> * I have no opinion on telling interrupt stack size by calling csi_interrupt_init functions.. I am just only  curious  to how many user know the value 's definion if they have no knowledge in low level..

I think that setting stack size for interrupt handling is not much different from setting stack sizes for the rest of the code.  It depends on the user's application (what depth of nested function calls, and how much data placed on the stack by functions run in interrupt service routines) so it can't be decided by RVM-CSI.

On the API there is an option to make mstack a NULL pointer, and specify zero size, in which case interrupts will use the stack of the code running when the interrupt was taken.  So the simple case of an M-mode only system with no special interrupt stack is allowed.  A BSP can implement such a system and not implement the U-mode stuff.  But it is more flexible to accommodate the possibility of 2 privilege modes on the API.

**Comment by WiseCrohn** [comment]
> * what would we take into account is how to help user develop secure application on MCU with two privilge (M & U) . it is better to do that at next stage.

Maybe we could start a discussion on the mailing list about this to see what other members think.

**Comment by ghost** [comment]
> > * I have no opinion on telling interrupt stack size by calling csi_interrupt_init functions.. I am just only  curious  to how many user know the value 's definion if they have no knowledge in low level..
> 
> I think that setting stack size for interrupt handling is not much different from setting stack sizes for the rest of the code. It depends on the user's application (what depth of nested function calls, and how much data placed on the stack by functions run in interrupt service routines) so it can't be decided by RVM-CSI.
> 
> On the API there is an option to make mstack a NULL pointer, and specify zero size, in which case interrupts will use the stack of the code running when the interrupt was taken. So the simple case of an M-mode only system with no special interrupt stack is allowed. A BSP can implement such a system and not implement the U-mode stuff. But it is more flexible to accommodate the possibility of 2 privilege modes on the API.

Agree.

**Comment by ghost** [comment]
> > * what would we take into account is how to help user develop secure application on MCU with two privilge (M & U) . it is better to do that at next stage.
> 
> Maybe we could start a discussion on the mailing list about this to see what other members think.

Do u know HEXFIVE ? I know they had it done.

**Comment by WiseCrohn** [comment]
> Do u know HEXFIVE ? I know they had it done.

No, can you give a link?

**Comment by ghost** [comment]
> > Do u know HEXFIVE ? I know they had it done.
> 
> No, can you give a link?

https://github.com/hex-five
Not sure they make it open source or not ..

**Comment by WiseCrohn** [comment]
> > > Do u know HEXFIVE ? I know they had it done.
> > 
> > 
> > No, can you give a link?
> 
> https://github.com/hex-five Not sure they make it open source or not ..

There is a question about whether we should be trying to help with porting this kind of TEE system between different RISC-V platforms, I don't know if that's practical.  But there are simpler cases where use of M/U modes is useful.  For example, even if not interested in security, some embedded developers are interested in using memory protection as a debugging tool or safety feature (i.e. use the PMP to ensure that code is not writing where it should not - which would indicate a bug).

**Comment by ghost** [comment]
> > > > Do u know HEXFIVE ? I know they had it done.
> > > 
> > > 
> > > No, can you give a link?
> > 
> > 
> > https://github.com/hex-five Not sure they make it open source or not ..
> 
> There is a question about whether we should be trying to help with porting this kind of TEE system between different RISC-V platforms, I don't know if that's practical. But there are simpler cases where use of M/U modes is useful. For example, even if not interested in security, some embedded developers are interested in using memory protection as a debugging tool or safety feature (i.e. use the PMP to ensure that code is not writing where it should not - which would indicate a bug).

yes, that's why  we must make a  clear definition for RVM-CSI scope..

**Review by ghost — APPROVED** [review]

**Pull request merged**
